### PR TITLE
Improve taginfo.json

### PR DESCRIPTION
**Pull request by goldfndr**
Add object types and icon URLs
I used dummyimage (free to use) rather than the images as they fill the icon a bit better; it's easy to switch to the images if preferred.
I moved 'diaper' to match its filter order.
I kept the descriptions last so that I didn't need to add/remove their commas.

### CODE REVIEW

**Comment by ValorNaram** [comment]
## Thank you for contributing to Babykarte

Contributions by people like you keep the project running and it's a great feedback for us. Your commit looks good in my eyes, you've also chosen the right branch. ( Saw your first proposal :( )

@Discostu36 now has to give his "yes" and we can merge it.

**Comment by goldfndr** [comment]
The filters.js I was viewing was the "master" one, not the "devel" one, so there are some additional edits to perform (e.g. access!=private). Hold off until next commit.

**Comment by goldfndr** [comment]
Well, it's nearly ready, except I suspect that proposed fix for #75 is buggy, as filter 11's first query isn't excluding diaper=no, just diaper=room and diaper=bench. Once that's resolved, there'll be two entries for Key:diaper, one for each filter.

**Comment by ValorNaram** [comment]
You're right, there was a bug in the feature #75. It has been solved and validated.

Thank you :(

**Comment by goldfndr** [comment]
Given the solution, there won't be duplication of the 'diaper' key, and this PR is ready.

**Comment by Discostu36** [comment]
Thanks for the PR. I'm not sure about the diaper entries. `POIs with this tag not shown on map (if not otherwise shown)` doesn't seem to be very valuable information to me. As I understand it, we should write into the file how we are processing these tags, not how we are **not** processing them. In my opinion `diaper=no` should be removed, `diaper:unisex` and` diaper:male` described as `Evaluated for 'baby friendliness' tab of POI pop-ups.`

**Comment by ValorNaram** [comment]
@Discostu36 can you write the appropriate description of how we process these tags? @goldfndr might don't know how we process these since he's not part of the development team and I assume he's not knowing/understanding the whole code and philosophy of this project as much as I (code)/we (philosophy).

Just push your changes to his branch and they will appear here. Once you finished you can merge this PR.

**Comment by goldfndr** [comment]
Okay, changes made.

**Comment by ValorNaram** [comment]
## Thank you for your time on this nice description for taginfo

**Pull request merged**
