### PR TITLE
Styling optimizations

### PR DESCRIPTION
**Pull request by claudiush**
- More compact sidebar, particularly on larger desktop screens to
- Language selector: Languages don't have flags. Use language code instead
- Sidebar: More consistent padding and margins for elements
- Popups content: Replaced drop shadow by border aligning to tab selection above
- Popup content: inactive tabs use opacity instead of grey background
- Removed version (0.2) from privacy link

### CODE REVIEW

**Comment by Discostu36** [comment]
Thank you very much for your work. But pull requests should always go to the devel branch, please, not to master.

**Comment by ValorNaram** [comment]
> Language selector: Languages don't have flags. Use language code instead

Yes that's true. In some cases this approach might not be correct but in most cases it is. Tutorials about making a website multilingual like [this one](https://www.wpbeginner.com/beginners-guide/how-to-easily-create-a-multilingual-wordpress-site/) are also showing this. I agree that this approach is not perfect but it works. We can add the name of the language next to the country icon in order to make it clearer. For most internet users it is clear.

PS: In the web designing community there's dispute about the use of country flag icons as identifiers for languages.

> Removed version (0.2) from privacy link

We use the version number to indicate which version of the privacy policy applies to which language. We do this so privacy concerned internet users who are willing to read a privacy policy can see when there's a new version of it.

> Popup content: inactive tabs use opacity instead of grey background

Funny! I also incorporated this in the current state of the Babykarte in the `devel` branch.

**Beside of my points:** Your changes are conflicting with the `devel` branch. Please resolve these conflicts first. These are preventing me from previewing and validating your changes.

**Comment by claudiush** [comment]
Will re-open following contribution guidelines.

**Comment by claudiush** [comment]
> PS: In the web designing community there's dispute about the use of country flag icons as identifiers for languages.

I'd strongly counter this: There is consensus in the UX community that flags do not represent languages in any case. Best summarized here: http://www.flagsarenotlanguages.com/blog/best-practice-for-presenting-languages/

**Comment by Discostu36** [comment]
I agree with that. I can imagine that a French Canadian might not be too happy to be summarized under a French flag.

**Comment by ValorNaram** [comment]
Ok

**Pull request closed without merging**
